<?php 






function insert_household_food_items_as_products() {
    // Check if the items have already been inserted (to prevent re-running the code)
    if (get_option('food_items_inserted') === 'yes') {
        return;
    }

  $household_food_items = [
    // Vegetables
    'Tomato',
    'Potato',
    'Onion',
    'Garlic',
    'Carrot',
    'Cucumber',
    'Bell Pepper',
    'Broccoli',
    'Cauliflower',
    'Spinach',
    'Lettuce',
    'Zucchini',
    'Eggplant',
    'Cabbage',
    'Celery',
    'Green Beans',
    'Peas',
    'Corn',
    'Mushroom',
    'Pumpkin',
    'Sweet Potato',
    'Radish',
    'Beetroot',
    'Leek',
    'Asparagus',
    'Turnip',
    'Artichoke',
    'Okra',
    'Chili Pepper',
    'Spring Onion',
    'Kale',
    'Arugula',
    'Swiss Chard',
    'Fennel',
    'Parsnip',
    'Brussels Sprouts',
    'Butternut Squash',
    'Yam',
    'Bok Choy',
    'Watercress',
    'Endive',
    'Collard Greens',
    'Mustard Greens',
    'Horseradish',
    'Daikon',
    'Jicama',
    'Rutabaga',
    'Scallion',

    // Fruits
    'Apple',
    'Banana',
    'Orange',
    'Lemon',
    'Lime',
    'Grapefruit',
    'Pineapple',
    'Mango',
    'Strawberry',
    'Blueberry',
    'Raspberry',
    'Blackberry',
    'Cherry',
    'Peach',
    'Plum',
    'Apricot',
    'Grape',
    'Watermelon',
    'Cantaloupe',
    'Honeydew',
    'Kiwi',
    'Papaya',
    'Passion Fruit',
    'Pomegranate',
    'Coconut',
    'Avocado',
    'Pear',
    'Fig',
    'Date',
    'Nectarine',
    'Tangerine',
    'Cranberry',
    'Gooseberry',
    'Guava',
    'Lychee',
    'Persimmon',
    'Star Fruit',
    'Dragon Fruit',
    'Jackfruit',
    'Durian',
    'Mulberry',
    'Olive',
    'Quince',
    'Rambutan',
    'Soursop',
    'Tamarind',
    'Ugli Fruit',
    'Yuzu',

    // Dairy
    'Milk',
    'Butter',
    'Cheddar Cheese',
    'Mozzarella Cheese',
    'Feta Cheese',
    'Parmesan Cheese',
    'Cream Cheese',
    'Yogurt',
    'Sour Cream',
    'Heavy Cream',
    'Cottage Cheese',
    'Ricotta Cheese',
    'Goat Cheese',
    'Blue Cheese',
    'Ghee',
    'Buttermilk',
    'Half and Half',
    'Evaporated Milk',
    'Condensed Milk',
    'Powdered Milk',

    // Meats & Proteins
    'Chicken Breast',
    'Chicken Thigh',
    'Ground Beef',
    'Steak',
    'Pork Chop',
    'Bacon',
    'Sausage',
    'Ham',
    'Turkey Breast',
    'Lamb Chop',
    'Duck',
    'Salmon',
    'Tuna',
    'Shrimp',
    'Crab',
    'Lobster',
    'Clams',
    'Mussels',
    'Oysters',
    'Eggs',
    'Tofu',
    'Tempeh',
    'Lentils',
    'Chickpeas',
    'Black Beans',
    'Kidney Beans',
    'Pinto Beans',
    'Navy Beans',
    'White Beans',
    'Soybeans',
    'Edamame',
    'Peanuts',
    'Almonds',
    'Cashews',
    'Walnuts',
    'Pecans',
    'Hazelnuts',
    'Pistachios',
    'Sunflower Seeds',
    'Pumpkin Seeds',
    'Chia Seeds',
    'Flaxseeds',
    'Hemp Seeds',

    // Grains & Breads
    'White Rice',
    'Brown Rice',
    'Basmati Rice',
    'Jasmine Rice',
    'Wild Rice',
    'Quinoa',
    'Barley',
    'Oats',
    'Rolled Oats',
    'Steel-Cut Oats',
    'Cornmeal',
    'Polenta',
    'Couscous',
    'Bulgur',
    'Millet',
    'Buckwheat',
    'White Bread',
    'Whole Wheat Bread',
    'Sourdough Bread',
    'Rye Bread',
    'Pita Bread',
    'Naan',
    'Bagel',
    'English Muffin',
    'Tortilla',
    'Flatbread',
    'Croissant',
    'Brioche',
    'Ciabatta',
    'Focaccia',
    'Baguette',
    'Muffin',
    'Pancake',
    'Waffle',
    'Cracker',
    'Breadstick',
    'Pretzel',
    'Doughnut',
    'Biscuit',
    'Scone',
    'Cornbread',
    'Rice Cake',

    // Pantry Staples
    'All-Purpose Flour',
    'Whole Wheat Flour',
    'Corn Flour',
    'Baking Powder',
    'Baking Soda',
    'Yeast',
    'Sugar',
    'Brown Sugar',
    'Powdered Sugar',
    'Salt',
    'Black Pepper',
    'Cinnamon',
    'Nutmeg',
    'Clove',
    'Cumin',
    'Coriander',
    'Turmeric',
    'Paprika',
    'Chili Powder',
    'Oregano',
    'Basil',
    'Thyme',
    'Rosemary',
    'Sage',
    'Bay Leaf',
    'Vanilla Extract',
    'Honey',
    'Maple Syrup',
    'Molasses',
    'Peanut Butter',
    'Almond Butter',
    'Jam',
    'Jelly',
    'Mustard',
    'Ketchup',
    'Mayonnaise',
    'Soy Sauce',
    'Hot Sauce',
    'Vinegar',
    'Apple Cider Vinegar',
    'Balsamic Vinegar',
    'White Vinegar',
    'Red Wine Vinegar',
    'Olive Oil',
    'Vegetable Oil',
    'Canola Oil',
    'Sesame Oil',
    'Coconut Oil',
    'Shortening',
    'Lard',
    'Stock Cubes',
    'Chicken Broth',
    'Beef Broth',
    'Vegetable Broth',
    'Tomato Paste',
    'Tomato Sauce',
        // Pantry Staples (continued)
    'Canned Tomatoes',
    'Canned Beans',
    'Canned Corn',
    'Canned Peas',
    'Canned Pineapple',
    'Canned Tuna',
    'Canned Salmon',
    'Canned Chicken',
    'Canned Soup',
    'Canned Mushrooms',
    'Canned Coconut Milk',
    'Canned Chili',
    'Canned Olives',
    'Canned Artichokes',
    'Instant Noodles',
    'Spaghetti',
    'Macaroni',
    'Penne',
    'Fusilli',
    'Linguine',
    'Fettuccine',
    'Lasagna Noodles',
    'Ramen',
    'Rice Noodles',
    'Egg Noodles',
    'Angel Hair Pasta',
    'Couscous',
    'Breadcrumbs',
    'Croutons',

    // Frozen Items
    'Frozen Peas',
    'Frozen Corn',
    'Frozen Spinach',
    'Frozen Broccoli',
    'Frozen Mixed Vegetables',
    'Frozen French Fries',
    'Frozen Onion Rings',
    'Frozen Berries',
    'Frozen Strawberries',
    'Frozen Blueberries',
    'Frozen Mango Chunks',
    'Frozen Pizza',
    'Frozen Chicken Nuggets',
    'Frozen Fish Fillets',
    'Frozen Shrimp',
    'Frozen Waffles',
    'Frozen Pancakes',
    'Frozen Dough',
    'Frozen Pie Crust',
    'Frozen Lasagna',
    'Frozen Burrito',
    'Frozen Meatballs',

    // Baking & Snacks
    'Chocolate Chips',
    'Cocoa Powder',
    'Cake Mix',
    'Vanilla Frosting',
    'Brownie Mix',
    'Cornstarch',
    'Gelatin',
    'Marshmallows',
    'Granola Bars',
    'Trail Mix',
    'Popcorn Kernels',
    'Microwave Popcorn',
    'Potato Chips',
    'Tortilla Chips',
    'Pretzels',
    'Crackers',
    'Rice Crackers',
    'Cookies',
    'Chocolate Bar',
    'Gummy Bears',
    'Hard Candy',
    'Licorice',
    'Pudding Mix',
    'Instant Oatmeal',
    'Cereal',
    'Granola',
    'Muesli',

    // Beverages
    'Water',
    'Sparkling Water',
    'Tonic Water',
    'Coconut Water',
    'Orange Juice',
    'Apple Juice',
    'Grape Juice',
    'Pineapple Juice',
    'Lemonade',
    'Iced Tea',
    'Green Tea',
    'Black Tea',
    'Chamomile Tea',
    'Coffee',
    'Instant Coffee',
    'Ground Coffee',
    'Coffee Beans',
    'Hot Chocolate Mix',
    'Tonic Water',
    'Herbal Tea',

    // Extra Items to reach 1000
    'Cooking Chocolate',
    'Rice Paper',
    'Nori Sheets',
    'Wasabi',
    'Miso Paste',
    'Canned Beansprouts',
    'Black Eyed Peas',
    'Instant Rice',
    'Frozen Pie',
    'Frozen Sweet Potatoes',
    'Frozen Sweet Corn',
    'Frozen Mixed Berries',
    'Sweetened Condensed Milk',
    'Cranberry Juice',
    'Salsa',
    'Hummus',
    'Tahini',
    'Sun-Dried Tomatoes',
    'Pickles',
    'Pesto',
    'BBQ Sauce',
    'Soy Sauce',
    'Teriyaki Sauce',
    'Fish Sauce',
    'Worcestershire Sauce',
    'Tabasco Sauce',
    'Chutney',
    'Fruit Jam',
    'Cinnamon Stick',
    'Vanilla Bean',
    'Curry Powder',
    'Garam Masala',
    'Bay Leaves',
    'Allspice',
    'Dill',
    'Cilantro',
    'Parsley',
    'Chives',
    'Mint Leaves',
    'Oregano Leaves',
    'Basil Leaves',
    'Rosemary Leaves',
    'Sage Leaves',
    'Thyme Leaves',
    'Pepperoni',
    'Salami',
    'Smoked Salmon',
    'Pancetta',
    'Prosciutto',
    'Rotisserie Chicken',
    'Frozen Chicken Wings',
    'Frozen Chicken Breast',
    'Frozen Sausage',
    'Frozen Fish Sticks',
    'Frozen Hash Browns',
    'Ice Cream',
    'Frozen Yogurt',
    'Cream',
    'Ricotta',
    'Provolone Cheese',
    'Swiss Cheese',
    'Cream',
    'Sour Cream',
];  

    // Loop through the array and create a product post for each item
    foreach ($household_food_items as $item) {
        // Insert a post for each item
        $post_id = wp_insert_post([
            'post_title'   => $item,                // Title of the product
            'post_type'    => 'product',             // Assuming the custom post type is 'product'
            'post_status'  => 'publish',             // Make sure the post is published
            'post_author'  => 1,                     // Adjust the post author if needed
        ]);
    }

    // Mark that the items have been inserted to prevent re-running
    update_option('food_items_inserted', 'yes');
}

// Run the function once
add_action('init', 'insert_household_food_items_as_products');
