import { Geist, Geist_Mono } from "next/font/google";
import { UserProvider } from "./contexts/UserContext";
import { OverlayProvider } from "./contexts/OverlayContext";
import { NotificationProvider } from "./contexts/NotificationContext";
import { ValidationProvider } from "./contexts/ValidationContext";
import { ListProvider } from "./contexts/ListContext";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<NotificationProvider>
					<ListProvider>
						<UserProvider>
							<ValidationProvider>
								<OverlayProvider>
									{children}
								</OverlayProvider>
							</ValidationProvider>
						</UserProvider>
					</ListProvider>
				</NotificationProvider>
			</body>
		</html>
	);
}